Node(int n:0..4847571).
Rank(int n:0..4847571, double rank).
Edge(int n:0..4847571, (int t)).
EdgeCnt(int n:0..4847571, int cnt).

Edge(s, t) :- l=$read("/home/gengl/Datasets/directed/LiveJournal-edge1_fix.txt"), (s1,s2)=$split(l, "	"),
             s=$toInt(s1), t=$toInt(s2).

EdgeCnt(s, $inc(1)) :- Edge(s, t).

Node(n) :- l=$read("/home/gengl/Datasets/nodes/LiveJournal-node.txt"), n=$toInt(l).

Rank(n, r) :- Node(n), r = 0.2 / 4847571.
Rank(y, $dsum(r1)) :- Rank(x, r), Edge(x, y),  EdgeCnt(x, d), r1 = 0.8 * r / d.
// /home/gengl/Datasets/directed/web-Google_fix.txt
// /home/gengl/Datasets/nodes/web-Google_fix_nodes.txt
// /home/gengl/socialite-mod/examples